language: python

python:
  - "3.5"
  - "3.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc devscripts debhelper python-setuptools

install:
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - python setup.py test
  - find -type f -name "*.py" | xargs flake8

after_success:
  - coverage run --source woudc_extcsv setup.py test
  - coverage report -m
  - debuild -b -uc -us
