environment:
  matrix:
    - PYTHON: "C:\\Python35"
      MINICONDA: "C:\\Miniconda3"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37"
      MINICONDA: "C:\\Miniconda3"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda update -q conda --yes
  - conda create -q -n appveyor-tests python=%PYTHON_VERSION% --yes
  - activate appveyor-tests
  - conda install --file requirements-dev.txt --yes
  - conda install -c conda-forge pyproj --yes
  - python setup.py install

build: off

test_script:
  - python setup.py test

on_success:
  - coverage.exe run --source woudc_extcsv setup.py test
  - coverage.exe report -m
